### ISSUE TITLE
Q : How to make pyvows running from ```setup.py test``` command ?

### ISSUE THREAD

**Issue by dhardy92** [heynemann/pyvows#122]
I would like to make 
```
python setup.py test
```
running pyvows tests in my projects.

How can I do this using test_loader or test_suite attribute ?

**Comment by coreypobrien** [comment]
There isn't a way currently for to make that in particular work because the test command uses the unittest runner. However, it would be possible to add support for a custom command like this:
```
python setup.py vows
```

**Comment by heynemann** [comment]
Done! :)
